### ISSUE TITLE
更新后点歌报错

### ISSUE THREAD

**Issue by ghost** [pcrbot/music#6]
[2020-09-08 12:49:23,046 nonebot] INFO: Self: 2842117629, Message -1006840945 from 1351495774@[群:1128254624]: '点歌 好日子'
[2020-09-08 12:49:23,046 music] INFO: Message -1006840945 triggered to_apply_for_title by PrefixTrigger.
[2020-09-08 12:49:23,568 music] ERROR: <class 'TypeError'> occured when to_apply_for_title handling message -1006840945.
[2020-09-08 12:49:23,568 music] ERROR: string indices must be integers
Traceback (most recent call last):
  File "/root/bot/HoshinoBot/hoshino/msghandler.py", line 39, in handle_message
    await sf.func(bot, event)
  File "/root/bot/HoshinoBot/hoshino/modules/music/music.py", line 80, in to_apply_for_title
    song_list = search_netease_cloud_music(music_name)
  File "/root/bot/HoshinoBot/hoshino/modules/music/music.py", line 181, in search_netease_cloud_music
    song_list = search163(music_name)
  File "/root/bot/HoshinoBot/hoshino/modules/music/search_netease_cloud_music.py", line 54, in search
    for item in data['result']['songs'][:result_num]:
TypeError: string indices must be integers

因为搜QQ正常，搜网易或点歌都会直接报错，怀疑是网易云的接口返回值为零导致。

**Comment by laipz8200** [comment]
本地未能复现，已在[7caa5a6](https://github.com/pcrbot/music/commit/7caa5a64cf802dd60bca7824aac3d0b64a0a66f0)中尝试修复。

`好日子`应该不会搜索不到结果，现版本对网易云搜索返回状态码同样有判断，暂不确定是否为触发了反爬机制，更新仅能避免报错跳出，若网易云搜索仍然无结果，建议降低使用频率，等待风控结束。
