### ISSUE TITLE
网易云点歌报错

### ISSUE THREAD

**Issue by yuban01652** [pcrbot/music#8]
多次尝试，网易云在点歌时有列表显示，选择歌曲后无反应报错，显示为timeout

[2020-09-09 16:30:03,458 music] ERROR: <class 'aiocqhttp.exceptions.NetworkError'> occured when choose_song handling message 86594.
[2020-09-09 16:30:03,458 music] ERROR: WebSocket API call timeout
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 118, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "/usr/local/python3/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/music/music.py", line 58, in choose_song
    await bot.send(ev, music)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 256, in send
    return await self.send_msg(**params)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 162, in call_action
    await ResultStore.fetch(seq, self._timeout_sec))
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 122, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout

**Comment by laipz8200** [comment]
此错误在bot将歌曲发送至QQ时发生，非插件导致。

请使用支持分享音乐的最新版[cqhttp-mirai](https://github.com/yyuueexxiinngg/cqhttp-mirai)或[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)。
